version: 2
jobs:
  test:
    docker:
      - image: centos:7
    steps:
      - checkout
      - run: ./install_test.sh
      - run: ./install.sh
      - run: ./grab_test.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - test
